#!/bin/bash

remote="$1"
url="$2"

# Specify your updated branch naming convention regex pattern
branch_naming_pattern="^refs/heads/(minor|patch|major)/[a-z0-9-]+$"

while read local_ref local_sha
do
    echo "ref is $local_ref"

    if [[ "$local_ref" == "refs/heads/main" ]]; then
        # Allow pushing to main branch without enforcing naming convention
        exit 0
    elif [[ "$local_ref" =~ $branch_naming_pattern ]]; then
        # Branch name follows the convention
        exit 0
    else
        # Branch name does not follow the convention
        echo "Error: Branch name does not follow the naming convention. It should start with 'minor/', 'patch/', or 'major/'."
        exit 1
    fi
done


# Check for a commit message matching the pattern
if git log --format=%B -n 1000 | grep -qE "Upgrade to [0-9]+\.[0-9]+\.[0-9]+ for reasons"; then
    echo "Version upgrade commit found. No action needed."
else
    echo "No version upgrade commit found. Running npm version patch..."
    npm version patch -m "Upgrade to %s for reasons"
fi
