name: Bump version tag and package.json
on:
    pull_request:
        types:
            - closed
        branches:
            - main

jobs:
    build:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.merge_commit_sha }}
                  fetch-depth: '0'
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
                  WITH_V: true

            - name: Bump Version Package Json
              uses: ramonpaolo/bump-version@v2.3.1
              env:
                  tag-name: git for-each-ref --sort=-v:refname --format '%(refname:lstrip=2)' | grep -E "$tagFmt" | head -n 1
              with:
                  tag: ${{ env.tag-name }}
                  commit: true
                  branch_to_push: 'main'
